### ISSUE TITLE
Feature: fine-grained enabled settings

### ISSUE THREAD

**Issue by jasonkuhrt** [brunch/auto-reload-brunch#14]
For instance:

```
autoReload:
  enabled:
    css: on
    html: off
    js: off
```
- off by default
- sugar for all-on: `enabled: true`
